version: 1
disable_existing_loggers: True

formatters:
    default:
        format: '%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: default
        stream: ext://sys.stderr
    timedRotatingFile:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: default
        when: H
        interval: 3
        # See discussion on backupCount decision: https://github.com/junhaoliao/iCtrl/pull/46/files/0c148d0e47dc9ae42014f10a4a04e0aaffca7cbd#r1921487166
        backupCount: 112
        # filename: To be dynamically assigned upon application initialization.

root:
    level: DEBUG
    handlers: [console, timedRotatingFile]
