version: 1
disable_existing_loggers: True

formatters:
    default:
        format: '%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    CLP_file:
        class: application.log_handlers.handlers.RotatingCLPFileHandler
        level: DEBUG
        formatter: default
        filename_prefix: 'ictrl'
        log_dir: 'logs'
        max_bytes: 5242880  # Rotate after 5 MB
        backup_count: 20  # Keep 20 backup files
        enable_compression: True
        timestamp_format: '%Y-%m-%d'

root:
    level: DEBUG
    handlers: [CLP_file]
